version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install PHP Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y zip unzip
            composer install
      - run:
          name: Install Node.js Dependencies
          command: |
            npm install
            npm run build

  deploy:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - run:
          name: Deploy to AWS
          command: |
            sudo apt-get install -y awscli
            aws deploy create-deployment --application-name <YourApplicationName> --deployment-group-name <YourDeploymentGroupName> --github-location repository=<YourGitHubRepository>,commitId=$CIRCLE_SHA1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
